site_name: KFO Wiki
repo_url: https://github.com/Killing-Fever-Online/KFO-Wiki
repo_name: Killing-Fever-Online/KFO-Wiki
edit_uri: https://prose.io/#Killing-Fever-Online/KFO-Wiki/edit/main/docs/
site_url: https://www.killingfeveronline.com/
theme:
  name: material
  # This thing will complain about the .ico format but the logo is valid anyway. Can just swap this out later.
  logo: img/favicon.ico
  favicon: img/favicon.ico
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: red
  features:
    - navigation.tabs
    - navigation.footer
    - toc.integrate
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.action.new
plugins:
  - search
  - social
  - awesome-nav
# extra_css:
#   - style.css